allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  puppeteer: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@ethersphere/bee-js@13.0.0-upcoming.g5647049'
overrides:
  '@solarpunkltd/file-manager-lib': link:../file-manager-lib
